---
# GitHub Dependabot configuration for go-covercheck
# Automatically creates pull requests to update dependencies

version: 2
updates:
  # Update Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "mach6"
    open-pull-requests-limit: 10

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "mach6"
    open-pull-requests-limit: 5

  # Update Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "docker"
      prefix-development: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "mach6"
    open-pull-requests-limit: 3
