version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst
