package comment

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mach6/go-covercheck/pkg/compute"
)

// maxRows caps the failing file and package tables so large projects stay under platform
// comment size limits (e.g. 65536 characters on GitHub).
const maxRows = 50

// FormatMarkdown renders results as a Markdown comment. failed is the overall outcome of the
// coverage check. With includeColors, pass/fail is shown with colored emoji; otherwise plain
// PASS/FAIL text is used.
func FormatMarkdown(results compute.Results, failed, includeColors bool) string {
	pass, fail := "PASS", "FAIL"
	if includeColors {
		pass, fail = "🟢", "🔴"
	}
	status := func(failed bool) string {
		if failed {
			return fail
		}
		return pass
	}

	var b strings.Builder
	b.WriteString(Marker + "\n")
	b.WriteString("## Coverage Report\n\n")

	if failed {
		fmt.Fprintf(&b, "%s **Coverage check failed**\n\n", status(true))
	} else {
		fmt.Fprintf(&b, "%s **Coverage check passed**\n\n", status(false))
	}

	t := results.ByTotal
	b.WriteString("### Total\n\n")
	b.WriteString("| Metric | Covered | Coverage | Threshold | Status |\n")
	b.WriteString("|--------|---------|----------|-----------|--------|\n")
	writeTotal := func(name, covered string, pct, threshold float64, failed bool) {
		fmt.Fprintf(&b, "| %s | %s | %.1f%% | %.1f%% | %s |\n", name, covered, pct, threshold, status(failed))
	}
	writeTotal("Statements", t.Statements.Coverage, t.Statements.Percentage, t.Statements.Threshold, t.Statements.Failed)
	writeTotal("Blocks", t.Blocks.Coverage, t.Blocks.Percentage, t.Blocks.Threshold, t.Blocks.Failed)
	writeTotal("Lines", t.Lines.Coverage, t.Lines.Percentage, t.Lines.Threshold, t.Lines.Failed)

	var files []namedBy
	for _, f := range results.ByFile {
		if f.Failed {
			files = append(files, namedBy{f.File, f.By})
		}
	}
	var pkgs []namedBy
	for _, p := range results.ByPackage {
		if p.Failed {
			pkgs = append(pkgs, namedBy{p.Package, p.By})
		}
	}
	writeFailing(&b, "Files Below Threshold", "File", files, status)
	writeFailing(&b, "Packages Below Threshold", "Package", pkgs, status)

	b.WriteString("\n---\n*Generated by [go-covercheck](https://github.com/mach6/go-covercheck)*\n")
	return b.String()
}

type namedBy struct {
	name string
	by   compute.By
}

func writeFailing(b *strings.Builder, title, column string, rows []namedBy, status func(bool) string) {
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })

	fmt.Fprintf(b, "\n### %s\n\n", title)
	fmt.Fprintf(b, "| %s | Statements | Blocks | Lines |\n", column)
	b.WriteString("|------|------------|--------|-------|\n")
	cell := func(pct, threshold float64) string {
		return fmt.Sprintf("%s %.1f%% / %.1f%%", status(pct < threshold), pct, threshold)
	}
	for i, r := range rows {
		if i == maxRows {
			fmt.Fprintf(b, "\n*…and %d more*\n", len(rows)-maxRows)
			break
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", codeCell(r.name),
			cell(r.by.StatementPercentage, r.by.StatementThreshold),
			cell(r.by.BlockPercentage, r.by.BlockThreshold),
			cell(r.by.LinePercentage, r.by.LineThreshold))
	}
}

// codeCell renders name as inline code that is safe inside a Markdown table cell.
func codeCell(name string) string {
	name = strings.ReplaceAll(name, "|", "\\|")
	if strings.Contains(name, "`") {
		return "`` " + name + " ``"
	}
	return "`" + name + "`"
}
