# module name for path normalization (overrides automatic module inference)
# useful when all packages share a common parent directory
# default "" (uses automatic inference via longest common prefix)
# moduleName: "github.com/mach6/go-covercheck"

# global threshold % for statement coverage.
# global default for per file %, per package %, and total %.
# default 70.
# disabled with 0
statementThreshold: 65.0

# global threshold % for block coverage.
# global default for per file %, per package %, and total %
# default 50.
# disabled with 0
blockThreshold: 60.0

# sortBy condition for table output formats.
# file|blocks|statements|statement-percent|block-percent
# default file
sortBy: statement-percent

# sortOrder direction for table output formats
# asc|desc
# default asc
sortOrder: desc

# disable table output and only show the summary
# default false
noTable: false

# disable the summary and only show the table output
# default false
noSummary: false

# disable use of color
# default false
noColor: false

# the format for output
# table|json|yaml|md|html|csv|tsv
# default table
format: table

# force output to the specified column width
# autoselected when <= 0
# default 0
terminalWidth: 0

# per-file threshold overrides
# default {"statements": {}, "blocks": {}}
# disabled with 0
perFile:
  statements:
#    main.go: 0
#    cmd/root.go: 32
  blocks:
#    main.go: 0
#    cmd/root.go: 20

# per-package threshold overrides
# default {"statements": {}, "blocks": {}}
# disabled with 0
perPackage:
  statements:
#    pkg/config: 10
  blocks:
#    pkg/config: 10
#    pkg/formatter: 0

# total threshold overrides
# default {"statements": statementThreshold, "blocks": blockThreshold}
# disabled with 0
total:
  statements: 65.0
  blocks: 60

# skip package(s) and/or file(s) regex
# default []
skip:
#  - cmd/root.go

# comment posting configuration for PR/MR comments
# default {"enabled": false}
comment:
  # enable comment posting to PR/MR
  # default false
  enabled: false
  
  platform:
    # platform type: github|gitlab|gitea|gogs
    # required when comment posting is enabled
    type: github
    
    # base URL for self-hosted instances
    # defaults: github.com, gitlab.com, or gitea.com
    # baseUrl: https://github.enterprise.com
    
    # authentication token for API access
    # required when comment posting is enabled
    # can also be set via --comment-token flag or environment variable
    # token: ghp_xxxxxxxxxxxxxxxxxxxx
    
    # repository identifier (owner/repo format)
    # required when comment posting is enabled
    # repository: owner/repo-name
    
    # pull request or merge request ID
    # required when comment posting is enabled
    # pullRequestId: 123
    
    # include color formatting in comments (emojis and markdown)
    # default true
    includeColors: true
    
    # update existing go-covercheck comment instead of creating new one
    # default false
    updateExisting: false
