name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Extract Tag and Set Version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "${TAG#v}" > VERSION

      - name: Make Dist
        run: make dist

      - name: Upload Dist Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Build Docker image
        run: make docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${GITHUB_REF#refs/tags/}
          docker tag go-covercheck:${TAG#v} $IMAGE_NAME:${TAG#v}
          docker tag go-covercheck:${TAG#v} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${TAG#v}
          docker push $IMAGE_NAME:latest

      - name: Update Changelog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          APP_VERSION="${GITHUB_REF#refs/tags/}" make changelog

      - name: Commit and Push Changelog As Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${TAG}"
          git checkout -b update_changelog_${TAG#v}
          git push origin update_changelog_${TAG#v}

          # Create a PR using gh CLI
          gh pr create --title "chore: update changelog for ${TAG}" \
            --body "Automated update to changelog for ${TAG}" \
            --head update_changelog_${TAG#v} \
            --base main

      - name: Update Homebrew Formula in homebrew-tap
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          SHA256=$(curl -sL https://github.com/mach6/go-covercheck/archive/refs/tags/${TAG}.tar.gz | sha256sum | cut -d' ' -f1)

          # Clone the tap repo using the token for authentication
          git clone https://mach6:${GH_TOKEN}@github.com/mach6/homebrew-tap.git
          cd homebrew-tap

          # Update the formula
          sed -i "s|url \".*\"|url \"https://github.com/mach6/go-covercheck/archive/refs/tags/${TAG}.tar.gz\"|" go-covercheck.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" go-covercheck.rb

          # Commit and push changes
          git checkout -b update-go-covercheck-${TAG}
          git add go-covercheck.rb
          git commit -m "Update go-covercheck formula for ${TAG}"
          git push origin update-go-covercheck-${TAG}

          # Create a PR using gh CLI
          gh pr create --title "Update go-covercheck formula for ${TAG}" \
            --body "Automated update for go-covercheck ${TAG}" \
            --head update-go-covercheck-${TAG} \
            --base main
