name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Make dist artifacts
        run: make dist

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Build Docker image
        run: make docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/go-covercheck
          TAG=${GITHUB_REF#refs/tags/}
          docker tag go-covercheck:latest $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:$TAG
