name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Extract Tag and Set Version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "${TAG#v}" > VERSION

      - name: Make Dist
        run: make dist

      - name: Upload Dist Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Build Docker image
        run: make docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${GITHUB_REF#refs/tags/}
          docker tag go-covercheck:${TAG#v} $IMAGE_NAME:${TAG#v}
          docker tag go-covercheck:${TAG#v} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${TAG#v}
          docker push $IMAGE_NAME:latest

      - name: Generate Changelog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          git-chglog -o CHANGELOG.md

      - name: Commit and Push Changelog As Branch
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git checkout -b update_changelog_${TAG#v}
          git push origin update_changelog_${TAG#v}
